[package]
name = "apalache_learn"
version = "0.1.0"
edition = "2024"

[dependencies]
tla-connect = { git = "https://github.com/NzSN/tla-connect-rs", features = ["rpc", "trace-validation"] }
serde = { version = "1", features = ["derive"] }
itf = "0.4"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"

[[example]]
name = "hourclock"
path = "examples/HourClock/hourclock.rs"

[[example]]
name = "hanoi"
path = "examples/Hanoi/hanoi.rs"

[[example]]
name = "simple_kv_cache"
path = "examples/SimpleKVCache/simple_kv_cache.rs"

[[example]]
name = "rb_tree"
path = "examples/RB-Tree/rb_tree.rs"
